sudo: required # will need superuser permission to execute this build
services:
  # will need docker-cli preinstall
  - docker

before_install:
  - docker build  -t umeshvjti/docker-react -f Dockerfile.dev .

script:
  - docker run umeshvjti/docker-react npm run test -- --coverage