sudo: required # will need superuser permission to execute this build
services:
  # will need docker-cli preinstall
  # travis will add supoort to docker to ou
  - docker

before_install:
  - docker build  -t umeshvjti/docker-react -f Dockerfile.dev .

script:
  - docker run umeshvjti/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk # travis ci comes pre configured to deploy application on aws EB
  region: "us-east-2" # region fow aws EB instance created in
  app: "docker-react" # aws EB application name
  env: "DockerReact-env" # aws environment name of application
  bucket_name: "elasticbeanstalk-us-east-2-131341973928" # s3 bucket where repo zip file is stored by travis
  bucket_path: "docker-react" # folder name in bucket
  on:
    branch: master # deploy only when new code is pushed to master
  access_key_id: $AWS_ACCESS_KEY # get the value from enviroment variable which is set in travis ci dashboard
  secret_access_key:
    secure: "$AWS_SECRET_KEY"